### ISSUE TITLE
Suggestion: test this library out with ert tests

### ISSUE THREAD

**Issue by ahyatt** [rolandwalker/string-utils#1]
This kind of library (which looks great, BTW), would be very easy and useful to test with ert tests.  That way, if new bugs come in, you can easily add tests for issues they raise.  And knowing that it is tested leads me to have higher confidence in the code.

**Comment by rolandwalker** [comment]
I agree on all points but it isn't something I have got around to.

Leaving this issue open; maybe someone will notice and send a pull request.

**Comment by rolandwalker** [comment]
added el-expectation tests in commit 69a6e1c5467b7951f508e2aaf29bcccd139c9459
